FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY backend/package*.json ./

RUN npm install --build-from-source

COPY backend/ .

RUN npm run build

EXPOSE 3000

CMD ["node", "dist/main.js"]